export const enum ReadingListActionTypes {
	GET_READING_LIST = 'GET_READING_LIST',
	ADD_BOOK_TO_READING_LIST = 'ADD_BOOK_TO_READING_LIST',
	REMOVE_BOOK_FROM_READING_LIST = 'REMOVE_BOOK_FROM_READING_LIST',
}
